/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dragonfire;

import java.rmi.RemoteException;

/**
 *
 * @author User
 */
public class BasicCards extends javax.swing.JFrame
{

    cardLogics cardLogic = new cardLogics();
    Network network = new Network();
    Utility util = new Utility();

    int Player;
    int Player2;

    /**
     * Creates new form BasicCards
     */
    public BasicCards()
    {
        initComponents();
        try
        {
            Player = network.Remote.assignPlayer();
            otherPlayer();
            System.out.println(Player);
            System.out.println(Player2);
        } catch (RemoteException e)
        {
            System.out.println("Something went wrong in the Constructor");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        MainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        yourHandList = new javax.swing.JList<>();
        opponentHand = new javax.swing.JLabel();
        deck = new javax.swing.JButton();
        shuffle = new javax.swing.JButton();
        refill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        yourHandList.setModel(cardLogic.myHand);
        yourHandList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        yourHandList.setCellRenderer(util.newCellRenderer());
        yourHandList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        yourHandList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        yourHandList.setVisibleRowCount(1);
        yourHandList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                yourHandListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(yourHandList);

        opponentHand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opponentHand.setText("Opponent Hand");

        deck.setText("DECK");
        deck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deckActionPerformed(evt);
            }
        });

        shuffle.setText("SHUFFLE");
        shuffle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                shuffleActionPerformed(evt);
            }
        });

        refill.setText("REFILL");
        refill.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(0, 145, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shuffle)
                            .addComponent(deck)
                            .addComponent(refill))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(opponentHand, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(310, 310, 310))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opponentHand)
                .addGap(147, 147, 147)
                .addComponent(shuffle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deckActionPerformed
    {//GEN-HEADEREND:event_deckActionPerformed
        try
        {
            if (cardLogic.myHand.size() < 5)
            {
                cardLogic.addCard(network.Remote.drawCardFromDeck(Player));
            }
        } catch (RemoteException e)
        {
            e.printStackTrace();
            //System.err.println("Something went wrong in the Draw Card from deck Action");
        }
    }//GEN-LAST:event_deckActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        try
        {
            network.Remote.disconnect(Player);
        } catch (RemoteException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void shuffleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_shuffleActionPerformed
    {//GEN-HEADEREND:event_shuffleActionPerformed
        try
        {
            network.Remote.shuffleDeck();
        } catch (RemoteException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_shuffleActionPerformed

    private void refillActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_refillActionPerformed
    {//GEN-HEADEREND:event_refillActionPerformed
        try
        {
            network.Remote.reset();
        } catch (RemoteException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_refillActionPerformed

    private void yourHandListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_yourHandListMouseClicked
    {//GEN-HEADEREND:event_yourHandListMouseClicked
        if(evt.getButton() == 1) {
//            System.out.println(evt.toString());
            cardLogic.myHand.remove(yourHandList.getSelectedIndex());
        }
    }//GEN-LAST:event_yourHandListMouseClicked

    public final void otherPlayer()
    {
        if (Player == 1)
        {
            Player2 = 2;
        } else if (Player == 2)
        {
            Player2 = 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BasicCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BasicCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BasicCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BasicCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BasicCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton deck;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel opponentHand;
    private javax.swing.JButton refill;
    private javax.swing.JButton shuffle;
    private javax.swing.JList<Card> yourHandList;
    // End of variables declaration//GEN-END:variables
}
